version: '3.8'

services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wp
      - pma
    networks:
      - cloud-network

  wp:
    image: wordpress:latest
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${DB_USERNAME}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_NAME=${DB_NAME}
    depends_on:
      - db
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - cloud-network

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - cloud-network

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=cloud
      - PMA_PASSWORD=cloud-pass
    depends_on:
      - db
    networks:
      - cloud-network

volumes:
  wordpress-data:
  mariadb-data:

networks:
  cloud-network:
    driver: bridge
